# Generated by Django 4.2.7 on 2023-11-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_rename_userprofile_usersprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersProfile',
            new_name='UserProfile',
        ),
    ]
