# Generated by Django 4.2.6 on 2023-11-01 03:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(help_text='试卷唯一识别号', primary_key=True, serialize=False, verbose_name='试卷id')),
                ('title', models.CharField(help_text='试卷标题', max_length=300, verbose_name='试卷标题')),
                ('answer', models.CharField(help_text='答案内容', max_length=300, verbose_name='答案内容')),
                ('score', models.FloatField(default=0, verbose_name='试卷总分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='PapersQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.papers')),
            ],
            options={
                'verbose_name': '试卷题目关系',
                'verbose_name_plural': '试卷题目关系',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(help_text='学生唯一识别号', primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(help_text='学生姓名', max_length=20, verbose_name='学生姓名')),
                ('score', models.FloatField(default=0, verbose_name='科目得分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.papers', verbose_name='所属试卷')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(help_text='问题唯一识别号', primary_key=True, serialize=False, verbose_name='问题id')),
                ('question', models.CharField(help_text='问题内容', max_length=300, verbose_name='问题内容')),
                ('answer', models.CharField(help_text='答案内容', max_length=300, verbose_name='答案内容')),
                ('score', models.FloatField(default=0, verbose_name='分数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('students', models.ManyToManyField(through='papers.PapersQuestions', to='papers.students', verbose_name='所属学生')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.AddField(
            model_name='papersquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.questions'),
        ),
        migrations.AddField(
            model_name='papersquestions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.students'),
        ),
        migrations.AddField(
            model_name='papers',
            name='questions',
            field=models.ManyToManyField(through='papers.PapersQuestions', to='papers.questions', verbose_name='包含的问题'),
        ),
    ]
