# Generated by Django 4.2.6 on 2023-11-13 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_answer_paper_question_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('answer', models.CharField(help_text='答案内容', max_length=300, verbose_name='答案内容')),
                ('score', models.FloatField(default=0, verbose_name='分数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(help_text='试卷唯一识别号', primary_key=True, serialize=False, verbose_name='试卷id')),
                ('title', models.CharField(help_text='试卷标题', max_length=300, verbose_name='试卷标题')),
                ('score', models.FloatField(default=0, verbose_name='试卷总分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('question_num', models.IntegerField(help_text='问题唯一识别号', verbose_name='问题num')),
                ('question', models.CharField(help_text='问题内容', max_length=300, verbose_name='问题内容')),
                ('score', models.FloatField(default=0, verbose_name='分数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.answers')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(help_text='学生唯一识别号', primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(help_text='学生姓名', max_length=20, verbose_name='学生姓名')),
                ('score', models.FloatField(default=0, verbose_name='科目得分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='papers',
            name='question',
            field=models.ManyToManyField(to='papers.questions'),
        ),
        migrations.AddField(
            model_name='papers',
            name='student',
            field=models.ManyToManyField(to='papers.students'),
        ),
    ]
