# Generated by Django 4.2.6 on 2023-11-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_answers_papers_questions_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='score',
        ),
    ]
